ai_classification_csv: C:\Users\willo\OneDrive - UNSW\Documents\Work\CES\Wild Deserts\Image
  classification\coding\id_app\config/config_2025-09-10.csv
folders: C:/Users/willo/OneDrive - UNSW/Documents/Work/CES/Wild Deserts/Image classification\WCAM99\outputs
output_dir: C:\Users\willo\OneDrive - UNSW\Documents\Work\CES\Wild Deserts\Image classification\coding\id_app\final_outputs/
parent_dir: C:/Users/willo/OneDrive - UNSW/Documents/Work/CES/Wild Deserts/Image classification
